rate/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

web/urls.py
from django.contrib import admin
from django.urls import path, include
from web import views

urlpatterns = [
    #path('admin/', admin.site.urls),
    path('hello', views.hello_world),
    path('now', views.now),

    path('registration',views.RegistrationView.as_view()),
    path("auth", views.auth_page, name="auth"),
    path('logout/', views.logout_view, name='logout'),

    path('profile/', views.profile, name='profile'),

    path('tournaments/', views.TournamentListView.as_view(), name='tournament_list'),
    path('tournaments/<int:pk>/', views.TournamentDetailView.as_view(), name='tournament_detail'),

    path('matches/', views.ListMatchView.as_view(), name = 'match_list'),
    path('match/<int:match_id>/add_comment/', views.add_comment, name='add_comment'),

    path('match_detail/<int:pk>/', views.MatchDetailView.as_view(), name='match_detail'),
    path('matches/<int:match_id>/bet/', views.create_bet, name='create_bet'),

    path('bets/<int:pk>/update/', views.BetUpdateView.as_view(), name='bet_update'),
    path('cancel_bet/<int:bet_id>/', views.cancel_bet, name='cancel_bet'),

    path('user_bets/', views.user_bets, name='user_bets'),
    path('add_balance/', views.add_balance, name='add_balance'),
    path('create_chat/<int:user_id>/', views.create_chat, name='create_chat'),
    path('user_list/', views.user_list, name='user_list'),
    path('user_detail/<int:user_id>/', views.user_detail, name='user_detail'),
    
    path('start_or_open_chat/<int:user_id>/', views.start_or_open_chat, name='start_or_open_chat'),

    path('chat/<int:chat_id>/', views.chat_view, name='chat_view'),


    path('accounts/', include('allauth.urls')),







    #path('matches/<int:pk>/', views.MatchDetailView.as_view(), name='match_detail'),
]

web/models.py
from django.utils import timezone

from django.db import models
from django.contrib.auth.models import UserManager as DjangoUserManager
from web.enums import Role
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class UserManager(DjangoUserManager):
    def _create_user(self, email, password, commit=True, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        if commit:
            user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        return self._create_user(email, password, role=Role.admin, **extra_fields)


class User(BaseModel, AbstractBaseUser, PermissionsMixin):
    objects = UserManager()
    image = models.ImageField(upload_to='images', null=True, blank=True)
    username = models.CharField( max_length=30, blank=True)

    email = models.EmailField(unique=True)
    role = models.CharField(choices=Role.choices, max_length=15, default=Role.user)
    name = models.CharField(max_length=255, null=True, blank=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, default=0)


    @property
    def is_staff(self):
        return self.role in (Role.admin, Role.staff)

    @property
    def is_superuser(self):
        return self.role == Role.admin

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "пользователь"
        verbose_name_plural = "пользователи"

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_photo = models.ImageField(upload_to='user_profiles/', blank=True, null=True)



class Sport(models.Model):
    keys = models.CharField(max_length=20, blank=True)
    name = models.CharField(max_length=100)
    description = models.TextField()

class Tournament(models.Model):
    creation_date = models.DateTimeField(default=timezone.now)  # Поле для хранения даты создания
    keyt = models.CharField(max_length=20, blank=True)
    name = models.TextField()

class Team(models.Model):
    name = models.CharField(max_length=100)
    sport = models.ForeignKey(Sport, on_delete=models.CASCADE, )
    description = models.TextField(default=None, blank=True)

class Match(models.Model):
    is_active = models.BooleanField(default=True)
    result = models.PositiveIntegerField(null=True)
    keym = models.CharField(max_length=20, blank=True)
    score_1 = models.IntegerField(default=0, blank=True, )
    score_2 = models.IntegerField(default=0, blank= True)
    oc1_rate = models.DecimalField(max_digits=6, decimal_places=3)
    oc2_rate = models.DecimalField(max_digits=6, decimal_places=3)
    oc3_rate = models.DecimalField(max_digits=6, decimal_places=3)
    tournament = models.ForeignKey(Tournament, on_delete = models.CASCADE)
    first_team = models.ForeignKey(Team, related_name='first_team', on_delete=models.CASCADE)
    second_team = models.ForeignKey(Team, related_name='second_team', on_delete=models.CASCADE)
    sport = models.ForeignKey(Sport, on_delete=models.CASCADE)
    is_payout_completed = models.BooleanField(default=False)


class Commentary(models.Model):
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()

class Bet(models.Model):
    is_winning = models.BooleanField(null=True)
    match = models.ForeignKey(Match, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    chosen_outcome = models.PositiveIntegerField(null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_cancelled = models.BooleanField(default=False)



"""class Outcome(models.Model):
    match = models.OneToOneField(Match, on_delete=models.CASCADE)
    result = models.PositiveIntegerField(null=True)"""

"""
class Payments(models.Model):
    bet = models.ForeignKey(Bet, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)"""

class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    transaction_type = models.CharField(max_length=20)
    
class Chat(models.Model):
    participants = models.ManyToManyField(User, related_name='chats')

class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, related_name='messages')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_messages')
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
# Create your models here.

web/templates/web/add_comment.html
{% extends 'web/index.html' %}
{% block title %}Добавление комментариев{% endblock %}

{% block content %}
    <section class="match">
      <h2>Add Comment</h2>
      <p>Match: {{ match.first_team.name }} vs {{ match.second_team.name }}</p>

      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
      </form>
      <a href="{% url 'match_detail' match.id %}">Back to Match Details</a>
    </section>
{% endblock %}

web/templates/web/bet_update.html
{% extends 'web/index.html' %}
{% block title %}Редактировать ставку{% endblock %}

{% block content %}
    <section class="auth">
    <h1 class="bet__h1">Редактировать ставку</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Сохранить изменения</button>
    </form>

{% if not bet.is_cancelled and  bet.match.is_active %}
    <form method="post" action="{% url 'cancel_bet' bet.id %}">
        {% csrf_token %}
        <button type="submit">Отменить ставку</button>
    </form>
{% endif %}
</section>
{% endblock %}

web/templates/web/chat.html
<!DOCTYPE html>
<html>
<head>
    <title>Chat</title>
</head>
<body>
    <div id="chat-log">
        <!-- Сюда будут выводиться сообщения чата -->
    </div>
    <input id="chat-message-input" type="text" placeholder="Введите сообщение">
    <button id="chat-message-submit">Отправить</button>

    <script>
        var chatSocket = new WebSocket(
            'ws://' + window.location.host +
            '/ws/chat/{{ chat_id }}/'
        );

        chatSocket.onmessage = function(e) {
            var data = JSON.parse(e.data);
            var message = data.message;
            document.querySelector('#chat-log').innerHTML += '<p>' + message + '</p>';
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // Enter key
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            var messageInputDom = document.querySelector('#chat-message-input');
            var message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

web/templates/web/index.html
<!DOCTYPE html>

{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'web/css/styles.css' %}">
</head>
<body>
            {% block content %}
            {% endblock %}
</body>
</html>

web/templates/web/match_detail.html
{% extends 'web/index.html' %}
{% block title %}Детали матча{% endblock %}

{% block content %}
    <section class="match">
    <h1>Детали матча</h1>

    <h2>{{ match.first_team.name}} vs {{ match.second_team.name }}</h2>

    <p>Спорт: {{ match.sport.name }}</p>
    <p>Турнир: {{ match.tournament.name }}</p>
    <p>Результат: {{ match.result }}</p>
    <p>Счет: {{ match.score_1 }} - {{ match.score_2 }}</p>
    <p>Ключ: {{ match.keym }}</p>
    <p>Ставки:</p>
    <ul>
        <li>Коэффициент 1: {{ match.oc1_rate }}</li>
        <li>Коэффициент 2: {{ match.oc2_rate }}</li>
        <li>Коэффициент 3: {{ match.oc3_rate }}</li>
    </ul>
        <a href="{% url 'create_bet' match_id=match.pk %}"> сделать ставку</a>
    <a href="{% url 'match_list' %}">Вернуться к списку матчей</a>
<form method="post" action="{% url 'add_comment' match.id %}">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button type="submit">Submit Comment</button>
  </form>

 <ul>
    {% for comment in match.commentary_set.all %}
      <li>{{ comment.user.name }} прокоментировал: {{ comment.comment }}</li>
    {% empty %}
      <li>No comments yet.</li>
    {% endfor %}
  </ul>
    </section>
{% endblock %}

web/templates/web/match_list.html
{% extends 'web/index.html' %}
{% block title %}Список матчей{% endblock %}

{% block content %}
    <section class="matches">
    <h1>Список матчей</h1>

    <ul>
        {% for match in matches %}
            <li>
                <a href="{% url 'match_detail' match.id %}">{{ match.first_team.name  }} vs {{ match.second_team.name  }}</a>
            </li>
        {% empty %}
            <li>На данный момент нет активных матчей.</li>
        {% endfor %}

                        <a class="exitButton" href="{% url 'profile'  %}">личный кабинет</a>

    </ul>

    </section>
{% endblock %}

web/templates/web/profile.html
{% extends 'web/index.html' %}
{% block title %}Личный кабинет{% endblock %}

{% block content %}
    <section class="lk">
        <h1>Личный кабинет</h1>

        <p>
            <img class="lk__img" src="{{ request.user.image.url }}">
            Имя: {{ request.user.name }}
        </p>
        <p>Email: {{ request.user.email }}</p>
        <p>Баланс: {{ request.user.balance }}</p>
        <a href="{% url 'tournament_list' %}">список всех турниров</a>
        <a href="{% url 'match_list' %}"> список матчей</a>
        <a href="{% url 'user_bets' %}"> ваши ставки</a>
        <a class="exitButton" href="{% url 'logout' %}">Выход</a>






        <a href="{% url 'add_balance' %}">Пополнить баланс</a>
    </section>

{% endblock %}

web/templates/web/registration.html
{% extends 'web/index.html' %}
{% block title %}Register{% endblock %}

{% block content %}

<form method="post" enctype="multipart/form-data"  class="register__form">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="file" name="image">
    <button type="submit">Зарегистрироваться</button>
</form>

{% endblock %}

web/templates/web/tournament_detail.html
{% extends 'web/index.html' %}
{% block title %}Детали матча{% endblock %}

{% block content %}
    <section class="match">
    <h1>{{ tournament.name }}</h1>
    <p>Дата создания: {{ tournament.creation_date }}</p>
    <p>Ключ: {{ tournament.keyt }}</p>

    {% for match in tournament.match_set.all %}
            <li class="list__tour">
                <a href="{% url 'match_detail' match.pk %}">{{ match.first_team.name }} vs {{ match.second_team.name }}</a>
            </li>
        {% endfor %}
    </ul>
    <!-- Добавьте другие поля турнира по вашему усмотрению -->

    <!-- Ссылка для возврата к списку турниров -->
    <a href="{% url 'tournament_list' %}">Вернуться к списку турниров</a>
    </section>
{% endblock %}

web/templates/web/tournament_list.html
{% extends 'web/index.html' %}
{% block title %}Список турниров{% endblock %}

{% block content %}
    <section class="matches">
    <h1>Список турниров</h1>
    <ul>
        {% for tournament in tournaments %}
            <li><a href="{% url 'tournament_detail' tournament.id %}">{{ tournament.name }}</a></li>
        {% endfor %}
        <a class="exitButton" href="{% url 'profile'  %}">личный кабинет</a>

    </ul>

    </section>
{% endblock %}

web/templates/web/user_bets.html
{% extends 'web/index.html' %}
{% block title %}Мои ставки{% endblock %}

{% block content %}
    <section class="matches">
    <h1>Мои ставки</h1>
    <ul>
        {% for bet in user_bets %}
            <li><a href="{% url 'bet_update' bet.pk %}">Ставка {{ bet.pk }}</a></li>
        {% endfor %}
    </ul>
</section>
{% endblock %}

web/templates/web/user_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Данные пользователя</title>
</head>
<body>
    <h1>Данные пользователя</h1>
    <p>Имя пользователя: {{ user.username }}</p>
    <p>Имя: {{ user.first_name }}</p>
    <p>Фамилия: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>

    <form action="{% url 'start_or_open_chat' user_id=user.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Перейти к диалогу</button>
    </form>


    <!-- Здесь вы можете добавить другие поля, которые вам нужны -->

    <a href="{% url 'user_list' %}">Вернуться к списку пользователей</a>
</body>
</html>

web/templates/web/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список пользователей</title>
</head>
<body>
    <h1>Список пользователей</h1>
    <ul>
        {% for user in users %}
            <li><a href="{% url 'user_detail' user_id=user.id %}">{{ user.name }}</a></li>
        {% endfor %}
    </ul>
</body>
</html>